# Generated by Django 4.2.7 on 2025-08-28 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='shop',
            name='business_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_license_document',
            field=models.FileField(blank=True, null=True, upload_to='business_documents/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_license_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='business_documents/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_certificate',
            field=models.FileField(blank=True, null=True, upload_to='business_documents/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('documents_submitted', 'Documents Submitted'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_shops', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Shop Created'), ('fee_paid', 'Join Fee Paid'), ('documents_submitted', 'Documents Submitted'), ('review_started', 'Review Started'), ('verified', 'Shop Verified'), ('rejected', 'Shop Rejected'), ('status_changed', 'Status Changed')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='shops.shop')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
